version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: cinema_db
    volumes:
      - ~/.pg/pg_data/yt:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5438:5438"
  api:
    container_name: cinema_api
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --no-input && gunicorn CoreRoot.wsgi:application --bind 0.0.0.0:8000"

volumes:
  static_volume:
  media_volume:
