version: "3.9"

services:
  db:
    image: postgres:14-alpine
    container_name: cinema_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  api:
    container_name: cinema_api
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --no-input && gunicorn CoreRoot.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: cinema_nginx
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/frontend/dist
      - static_volume:/yt/static
      - media_volume:/yt/media

  memcached:
    image: memcached:alpine
    container_name: cinema_memcached
    ports:
      - "11211:11211"
    restart: always

volumes:
  static_volume:
  media_volume:
  postgres_data:
