version: '3.9'

services:
  redis:
    image: redis:alpine
  nginx:
    container_name: cinema_web
    restart: on-failure
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    container_name: cinema_api
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --no-input && gunicorn CoreRoot.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    container_name: cinema_db
    image: postgres:16-alpine
    env_file: .env