# Generated by Django 5.0.4 on 2024-05-13 10:57

import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='poster/%Y/%m/%d')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('age_limit', models.CharField(choices=[('0+', 'Zero'), ('6+', 'Six'), ('12+', 'Twelve'), ('16+', 'Sixteen'), ('18+', 'Eighteen')], max_length=3)),
                ('actors', models.ManyToManyField(to='core_person.person')),
            ],
            options={
                'db_table': "'core.film'",
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
