# Generated by Django 5.0.4 on 2024-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0001_initial'),
        ('core_person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(to='core_person.person'),
        ),
    ]
