# Generated by Django 5.0.4 on 2024-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
