# Generated by Django 5.0.4 on 2024-05-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0002_film_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='poster/%Y/%m/%d'),
        ),
    ]
