# Generated by Django 5.0.4 on 2024-05-16 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0002_remove_film_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='average_rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
