# Generated by Django 5.0.4 on 2024-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0002_film_actors'),
        ('core_person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='core_person.person'),
        ),
    ]
