# Generated by Django 5.0.4 on 2024-05-16 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0003_film_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='average_rating',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
