# Generated by Django 5.0.4 on 2024-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0004_alter_film_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
