# Generated by Django 5.0.4 on 2024-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0004_alter_film_average_rating'),
        ('core_genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='film',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='core_genre.genre'),
        ),
    ]
