# Generated by Django 5.0.4 on 2024-10-03 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0005_alter_film_managers_remove_film_genre_film_genre'),
        ('core_genre', '0001_initial'),
        ('core_person', '0002_person_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='films', to='core_person.person'),
        ),
        migrations.AlterField(
            model_name='film',
            name='age_limit',
            field=models.CharField(choices=[('0+', 'Zero years'), ('6+', 'Six years'), ('12+', 'Twelve years'), ('16+', 'Sixteen years'), ('18+', 'Eighteen years')], max_length=3),
        ),
        migrations.AlterField(
            model_name='film',
            name='average_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='core_genre.genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='poster/%Y/%m/%d'),
        ),
        migrations.AlterModelTable(
            name='film',
            table='core.film',
        ),
    ]
