# Generated by Django 5.0.4 on 2024-05-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0005_film_description_film_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
