# Generated by Django 5.0.4 on 2024-09-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0005_alter_film_managers_remove_film_genre_film_genre'),
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='films_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_film.film'),
        ),
    ]
