# Generated by Django 5.0.4 on 2024-10-03 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_films_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='films_liked',
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
